---
- name: EC2 keypair
  local_action:
    module: ec2_key
    name: hsl-liipi
    region: eu-west-1
  register: ec2_keypair

- name: store potential new key
  copy: content="{{ec2_keypair.key.private_key}}" dest="hsl-liipi.key" mode=0400
  when: ec2_keypair.changed == True

- name: EC2 instance liipi-ci
  local_action:
    module: ec2
    key_name: hsl-liipi
    group: hsl-liipi-internal
    instance_type: m3.medium
    image: ami-3907d64e
    vpc_subnet_id: "{{vpc_dev_subnet_id}}"
    wait: yes
    wait_timeout: 500
    instance_tags:
       Name: liipi-ci
    count_tag:
       Name: liipi-ci
    exact_count: 1
    monitoring: no
    region: eu-west-1

- name: EC2 instance liipi-test
  local_action:
    module: ec2
    key_name: hsl-liipi
    group: hsl-liipi-internal
    instance_type: m3.medium
    image: ami-3907d64e
    vpc_subnet_id: "{{vpc_dev_subnet_id}}"
    wait: yes
    wait_timeout: 500
    instance_tags:
       Name: liipi-test
    count_tag:
       Name: liipi-test
    exact_count: 1
    monitoring: no
    region: eu-west-1
